server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#        search-locations: "classpath:/config"
        git:
          uri: "https://github.com/vishnunair279/microservices-config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
